### ISSUE TITLE
plotBPs recovery y-axis

### ISSUE THREAD

**Issue by niafall** [iagomosqueira/WKREBUILD_toolset#17]
Would it be possible to constrain the y-axes on the "recovery" panel of plotBPs so that it only shows the range over which simulations are run (or something else more clever than that)? It might make it easier to compare performance between OMs/scenarios.

**Comment by iagomosqueira** [comment]
Yes, that statistic is different from the others so the plot does not quite work.  A quick hack would be to adjust the ylim for only that facet, which can be done using the *gg4hx* package.

```
library(ggh4x)

plotBPs(perf[year=='all']) + ylim(c(0, NA)) +
  facetted_pos_scales(y = list(
  name == "recovery" ~ scale_y_continuous(limits = c(2022, 2030))))
```

**Comment by niafall** [comment]
Ah - great stuff, thanks, @iagomosqueira
